/* autogenerated by generator-region.js */

#pragma once

#include <nan.h>
#include <node.h>
#include <girepository.h>
#include <glib.h>
#include <cairo.h>

namespace GNodeJS {

namespace Cairo {


class Region: public Nan::ObjectWrap {
  public:
    static Nan::Persistent<v8::FunctionTemplate> constructorTemplate;
    static Nan::Persistent<v8::Function>         constructor;
    static void Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE target);
    static void SetupTemplate();
    static Local<v8::FunctionTemplate> GetTemplate();
    static Local<v8::Function> GetConstructor();

    static NAN_METHOD(New);

    static NAN_METHOD(copy);
    static NAN_METHOD(status);
    static NAN_METHOD(getExtents);
    static NAN_METHOD(numRectangles);
    static NAN_METHOD(getRectangle);
    static NAN_METHOD(isEmpty);
    static NAN_METHOD(containsPoint);
    static NAN_METHOD(containsRectangle);
    static NAN_METHOD(equal);
    static NAN_METHOD(translate);
    static NAN_METHOD(intersect);
    static NAN_METHOD(intersectRectangle);
    static NAN_METHOD(subtract);
    static NAN_METHOD(subtractRectangle);
    static NAN_METHOD(union_);
    static NAN_METHOD(unionRectangle);
    static NAN_METHOD(xor_);
    static NAN_METHOD(xorRectangle);

    Region(cairo_region_t* data);
    ~Region();

    cairo_region_t* _data;
};


}; // Cairo

}; // GNodeJS